version: "3.7"
services:

  backend:
    build: ./app
    command: ["/app/tools/run.sh"]
    volumes:
      - static_volume:/app/staticfiles
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "pass"
      ADMIN_EMAIL: "admin@example.com"
      DATABASE_URL: "postgres://doccano:doccano@postgres:5432/doccano?sslmode=disable"
      ALLOW_SIGNUP: "False" #変更Trueに
      DEBUG: "False"
    depends_on:
      - postgres
    networks:
      - network-backend
      - network-frontend

  frontend:
    build: ./frontend
    volumes:
      - www:/app/dist
    environment:
      GOOGLE_TRACKING_ID: ""


  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - www:/var/www/html:ro
  #     - static_volume:/static
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend
  #   networks:
  #     - network-frontend

      
  #  以下追加###
  https-portal:
    build:
        context: ./Docker/https-portal
        dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./log:/var/log/nginx
      - www:/var/www/html:ro
      - static_volume:/static
    depends_on:
      - backend
    environment:
      STAGE: 'local'
      TZ: 'Asia/Tokyo'
      ERROR_LOG: default
      ACCESS_LOG: default
    networks:
      - network-frontend
  ## 

  

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "doccano"
      POSTGRES_PASSWORD: "doccano"
      POSTGRES_DB: "doccano"
    networks:
      - network-backend

volumes:
  postgres_data:
  static_volume:
  www:

networks:
  network-backend:
  network-frontend:
